export const properties = [
  {
    id: 'ref-007',
    type: 'Casa',
    status: 'Usado',
    price: 340000000,
    title: 'Casa en Venta en Sector Las Américas',
    location: 'Armenia, Quindío, Colombia',
    beds: 3,
    baths: 3,
    parking: 2,
    parkingType: 'Cubierto',
    areaConstruida: 125,
    areaPrivada: 125,
    areaTerreno: 125,
    estrato: 3,
    pisos: 2,
    antiguedad: '0-5 años',
    remodelado: 'No',
    permuta: 'No',
    sector: 'Las Américas',
    enConjunto: 'No',
    mapEmbedUrl: 'https://maps.google.com/maps?q=Barrio+Las+Americas+Armenia+Quindio+Colombia&t=&z=15&ie=UTF8&iwloc=&output=embed',
    videoUrl: 'https://drive.google.com/open?id=1dtWe3FSP2A5peNauQ7B9LmWcuhmELZzt',
    videoEmbedUrl: 'https://drive.google.com/file/d/1dtWe3FSP2A5peNauQ7B9LmWcuhmELZzt/preview',
    description: 'Hermosa casa de 2 niveles ubicada en el prestigioso y tranquilo sector de Las Américas en Armenia, Quindío. La propiedad cuenta con sala espaciosa, comedor independiente, cocina integral, 3 cómodas habitaciones, 3 baños completos, zona de ropas, patio privado y parqueadero cubierto para 2 vehículos. Sector de alta valorización con vías pavimentadas y excelente conectividad.',
    mainImg: '/properties/ref-007/foto_4.jpg',
    images: [
      '/properties/ref-007/foto_3.jpg',
      '/properties/ref-007/foto_1.jpg',
      '/properties/ref-007/foto_2.jpg',
      '/properties/ref-007/foto_5.jpg',
      '/properties/ref-007/foto_6.jpg',
      '/properties/ref-007/foto_8.jpg',
      '/properties/ref-007/foto_11.jpg',
      '/properties/ref-007/foto_7.jpg',
      '/properties/ref-007/foto_9.jpg',
      '/properties/ref-007/foto_12.jpg',
      '/properties/ref-007/foto_10.jpg'
    ],
    features: [
      'Sala y comedor independientes',
      'Cocina integral',
      'Zona de ropas',
      'Patio privado',
      'Parqueadero cubierto (2 autos)',
      'Sector tranquilo',
      'Alta valorización',
      'Vías pavimentadas de fácil acceso',
      'Cerca a supermercados y droguerías',
      'Cerca a bancos y cajeros automáticos',
      'Cerca a gimnasios y colegios',
      'Parques y transporte público cercano'
    ]
  },
  {
    id: 'ref-001',
    type: 'Casa',
    status: 'Usado',
    price: 850000000,
    title: 'Casa Moderna en Zona Norte',
    location: 'Bogotá, Colombia',
    beds: 3,
    baths: 3,
    parking: 2,
    parkingType: 'Cubierto',
    areaConstruida: 180,
    areaPrivada: 125,
    areaTerreno: 200,
    estrato: 4,
    pisos: 2,
    antiguedad: '1 a 8 años',
    remodelado: 'Sí',
    permuta: 'No',
    sector: 'Zona Norte',
    enConjunto: 'Sí',
    mapEmbedUrl: 'https://maps.google.com/maps?q=Usaquen+Bogota+Colombia&t=&z=14&ie=UTF8&iwloc=&output=embed',
    description: 'Hermosa casa moderna ubicada en exclusivo sector del norte de Bogotá. Cuenta con amplios espacios iluminados naturalmente, cocina tipo americano con acabados de lujo, sala comedor integrados, jardín privado, estudio y zona de ropas independiente. Conjunto cerrado con vigilancia 24/7 y excelentes zonas comunes.',
    mainImg: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80'
    ],
    features: ['Piscina', 'Gimnasio', 'Salón social', 'Zonas verdes', 'Vigilancia 24/7', 'Alta valorización', 'Cerca a centros comerciales', 'Cámaras de seguridad', 'Parqueadero de visitantes']
  },
  {
    id: 'ref-002',
    type: 'Apartamento',
    status: 'Usado',
    price: 650000000,
    title: 'Apartamento Vista Panorámica El Poblado',
    location: 'Medellín, Colombia',
    beds: 2,
    baths: 2,
    parking: 1,
    parkingType: 'Cubierto',
    areaConstruida: 95,
    areaPrivada: 90,
    areaTerreno: 0,
    estrato: 5,
    pisos: 1,
    antiguedad: 'Menos de 1 año',
    remodelado: 'No',
    permuta: 'No',
    sector: 'El Poblado',
    enConjunto: 'Sí',
    mapEmbedUrl: 'https://maps.google.com/maps?q=El+Poblado+Medellin+Colombia&t=&z=14&ie=UTF8&iwloc=&output=embed',
    description: 'Espectacular apartamento en piso alto con vista ininterrumpida a las montañas de Medellín. Diseño contemporáneo de concepto abierto, balcón panorámico amplio, acabados premium y cocina integral equipada. Edificio con amenidades de club house.',
    mainImg: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1512918580421-df13b2c6eeb4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80'
    ],
    features: ['Gimnasio', 'Balcón panorámico', 'Vigilancia 24/7', 'Cerca a centros comerciales', 'Excelentes vías de acceso', 'Piscina sinfín', 'Coworking']
  },
  {
    id: 'ref-003',
    type: 'Lote',
    status: 'Nuevo',
    price: 320000000,
    title: 'Lote Campestre Exclusivo',
    location: 'Eje Cafetero, Colombia',
    beds: 0,
    baths: 0,
    parking: 0,
    parkingType: 'N/A',
    areaConstruida: 1500,
    areaPrivada: 0,
    areaTerreno: 1500,
    estrato: 3,
    pisos: 0,
    antiguedad: 'N/A',
    remodelado: 'N/A',
    permuta: 'Sí',
    sector: 'Campestre',
    enConjunto: 'Sí',
    mapEmbedUrl: 'https://maps.google.com/maps?q=Quimbaya+Quindio+Colombia&t=&z=13&ie=UTF8&iwloc=&output=embed',
    description: 'Terreno campestre con topografía ideal y clima templado en el corazón del Eje Cafetero. Ubicado en parcelación campestre de alta categoría con vías pavimentadas, acueducto propio, red eléctrica subterránea y vista privilegiada al paisaje cafetero.',
    mainImg: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1448375240586-882707db888b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80'
    ],
    features: ['Zonas verdes', 'Vigilancia 24/7', 'Alta valorización', 'Entorno seguro y campestre', 'Servicios públicos disponibles', 'Vías pavimentadas']
  },
  {
    id: 'ref-004',
    type: 'Apartamento',
    status: 'Usado',
    price: 520000000,
    title: 'Apartamento de Lujo con Terraza',
    location: 'Barranquilla, Colombia',
    beds: 3,
    baths: 2,
    parking: 2,
    parkingType: 'Cubierto',
    areaConstruida: 120,
    areaPrivada: 110,
    areaTerreno: 0,
    estrato: 6,
    pisos: 1,
    antiguedad: '1 a 8 años',
    remodelado: 'Sí',
    permuta: 'No',
    sector: 'Altos de Riomar',
    enConjunto: 'Sí',
    mapEmbedUrl: 'https://maps.google.com/maps?q=Altos+de+Riomar+Barranquilla+Colombia&t=&z=14&ie=UTF8&iwloc=&output=embed',
    description: 'Exclusivo apartamento en el sector más cotizado de Barranquilla. Gran terraza con vista a la brisa caribeña, acabados en porcelanato, iluminación LED inteligente y alcoba principal con vestier y baño privado.',
    mainImg: 'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502005229762-ee1b2b93e000?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80'
    ],
    features: ['Piscina', 'Gimnasio', 'Balcón / Terraza', 'Vigilancia 24/7', 'Alta valorización', 'Planta eléctrica total', 'Zona infantil']
  },
  {
    id: 'ref-005',
    type: 'Casa',
    status: 'Usado',
    price: 950000000,
    title: 'Casa Familiar Amplia con Jardín',
    location: 'Cali, Colombia',
    beds: 4,
    baths: 3,
    parking: 3,
    parkingType: 'Cubierto',
    areaConstruida: 220,
    areaPrivada: 200,
    areaTerreno: 250,
    estrato: 5,
    pisos: 3,
    antiguedad: '9 a 15 años',
    remodelado: 'Sí',
    permuta: 'Sí',
    sector: 'Ciudad Jardín / Pance',
    enConjunto: 'Sí',
    mapEmbedUrl: 'https://maps.google.com/maps?q=Ciudad+Jardin+Cali+Colombia&t=&z=14&ie=UTF8&iwloc=&output=embed',
    description: 'Imponente casa familiar en condominio campestre en Cali. Amplios jardines internos, zona BBQ techada, 4 cómodas habitaciones, sala de estar independiente y acabados en madera maciza restaurada.',
    mainImg: 'https://images.unsplash.com/photo-1449844908441-8829872d2607?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80'
    ],
    features: ['Jardín privado', 'Estudio', 'Zonas verdes', 'Colegios cercanos', 'Entorno seguro y residencial', 'Zona BBQ', 'Portería 24h']
  },
  {
    id: 'ref-006',
    type: 'Apartamento',
    status: 'Nuevo',
    price: 430000000,
    title: 'Apartamento Studio Moderno',
    location: 'Bucaramanga, Colombia',
    beds: 1,
    baths: 2,
    parking: 1,
    parkingType: 'Cubierto',
    areaConstruida: 62,
    areaPrivada: 58,
    areaTerreno: 0,
    estrato: 4,
    pisos: 1,
    antiguedad: 'A estrenar',
    remodelado: 'No',
    permuta: 'No',
    sector: 'Cabecera del Llano',
    enConjunto: 'Sí',
    mapEmbedUrl: 'https://maps.google.com/maps?q=Cabecera+del+Llano+Bucaramanga+Colombia&t=&z=14&ie=UTF8&iwloc=&output=embed',
    description: 'Apartamento moderno tipo loft a estrenar. Ideal para inversionistas o jóvenes profesionales. Excelente iluminación, balcón privado y acceso a terraza comunitaria con vista 360 grados.',
    mainImg: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80'
    ],
    features: ['Rooftop con BBQ', 'Gimnasio', 'Vigilancia 24/7', 'Ascensor', 'Cerca a universidades y centros médicos']
  }
];
