export const properties = [
  {
    id: 'ref-001',
    type: 'Casa',
    status: 'Usado',
    price: 340000000,
    title: 'Casa en Venta en Sector Las Américas',
    location: 'Armenia, Quindío, Colombia',
    beds: 3,
    baths: 3,
    parking: 2,
    parkingType: 'Cubierto',
    areaConstruida: 125,
    areaPrivada: 125,
    areaTerreno: 125,
    estrato: 3,
    pisos: 2,
    antiguedad: '0-5 años',
    remodelado: 'No',
    permuta: 'No',
    sector: 'Las Américas',
    enConjunto: 'No',
    lat: 4.5428,
    lng: -75.6792,
    zoom: 15,
    zoneRadius: 400,
    mapEmbedUrl: 'https://maps.google.com/maps?q=Barrio+Las+Americas+Armenia+Quindio+Colombia&t=&z=15&ie=UTF8&iwloc=&output=embed',
    videoUrl: 'https://drive.google.com/open?id=1dtWe3FSP2A5peNauQ7B9LmWcuhmELZzt',
    videoEmbedUrl: 'https://drive.google.com/file/d/1dtWe3FSP2A5peNauQ7B9LmWcuhmELZzt/preview',
    description: 'Hermosa casa de 2 niveles ubicada en el prestigioso y tranquilo sector de Las Américas en Armenia, Quindío. La propiedad cuenta con sala espaciosa, comedor independiente, cocina integral, 3 cómodas habitaciones, 3 baños completos, zona de ropas, patio privado y parqueadero cubierto para 2 vehículos. Sector de alta valorización con vías pavimentadas y excelente conectividad.',
    mainImg: '/properties/ref-001/foto_4.jpg',
    images: [
      '/properties/ref-001/foto_3.jpg',
      '/properties/ref-001/foto_1.jpg',
      '/properties/ref-001/foto_2.jpg',
      '/properties/ref-001/foto_5.jpg',
      '/properties/ref-001/foto_6.jpg',
      '/properties/ref-001/foto_8.jpg',
      '/properties/ref-001/foto_11.jpg',
      '/properties/ref-001/foto_7.jpg',
      '/properties/ref-001/foto_9.jpg',
      '/properties/ref-001/foto_12.jpg',
      '/properties/ref-001/foto_10.jpg'
    ],
    features: [
      'Sala y comedor independientes',
      'Cocina integral',
      'Zona de ropas',
      'Patio privado',
      'Parqueadero cubierto (2 autos)',
      'Sector tranquilo',
      'Alta valorización',
      'Vías pavimentadas de fácil acceso',
      'Cerca a supermercados y droguerías',
      'Cerca a bancos y cajeros automáticos',
      'Cerca a gimnasios y colegios',
      'Parques y transporte público cercano'
    ]
  },
  {
    id: 'ref-002',
    type: 'Aparta estudio',
    status: 'Nuevo',
    price: 130000000,
    title: 'Apartaestudio Nuevo en Sector Pinares',
    location: 'Armenia, Quindío, Colombia',
    beds: 1,
    baths: 1,
    parking: 0,
    parkingType: 'No asignado',
    areaConstruida: 39,
    areaPrivada: 39,
    areaTerreno: 39,
    estrato: 2,
    pisos: 1,
    pisoNumero: 1,
    antiguedad: '0-5 años',
    remodelado: 'No',
    permuta: 'No',
    sector: 'Pinares',
    enConjunto: 'No',
    lat: 4.5485,
    lng: -75.6695,
    zoom: 15,
    zoneRadius: 350,
    mapEmbedUrl: 'https://maps.google.com/maps?q=Pinares+Armenia+Quindio+Colombia&t=&z=15&ie=UTF8&iwloc=&output=embed',
    videoUrl: 'https://drive.google.com/open?id=1hMu0Uxcsm2YTm2p8x4ntUdZSotUlwVLP',
    videoEmbedUrl: 'https://drive.google.com/file/d/1hMu0Uxcsm2YTm2p8x4ntUdZSotUlwVLP/preview',
    description: 'Excelente apartaestudio a estrenar ubicado en el primer piso sobre vía principal en el sector de Pinares, Armenia. Cuenta con 39 m² perfectamente distribuidos con sala, comedor, cocina integral moderna, amplia habitación con closet, baño completo con excelentes acabados, zona de ropas independiente y patio interior. Destaca por sus finos pisos en porcelanato, conexión de gas natural y abundante iluminación natural en todos sus ambientes. Oportunidad ideal de inversión o vivienda propia.',
    mainImg: '/properties/ref-002/foto_1.jpg',
    images: [
      '/properties/ref-002/foto_3.jpg',
      '/properties/ref-002/foto_4.jpg',
      '/properties/ref-002/foto_5.jpg',
      '/properties/ref-002/foto_6.jpg',
      '/properties/ref-002/foto_7.jpg',
      '/properties/ref-002/foto_8.jpg',
      '/properties/ref-002/foto_2.jpg'
    ],
    features: [
      'Ubicación en primer piso',
      'Sobre vía principal',
      'Cocina integral equipada',
      'Pisos en porcelanato de alta calidad',
      'Habitación con closet empotrado',
      'Gas natural instalado',
      'Iluminación y ventilación natural',
      'Zona de ropas y patio interior',
      'Sala y comedor integrados',
      'Excelente conectividad y transporte público',
      'Sector de alta demanda y valorización',
      'Inmueble totalmente nuevo (0 a 5 años)'
    ]
  }
];
